name: landa_messenger_api
description: Landa Messenger Dart API
version: 1.0.0
homepage: https://landamessenger.com/

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5           # android   ios   linux   macos   web   windows
  stack_trace: ^1.11.0    # android   ios   linux   macos   web   windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
